//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANG_EMPLOYEE
    {
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string email { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string ContactPreference { get; set; }
        public Nullable<System.DateTime> dateofBirth { get; set; }
        public string department { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string PhotoPath { get; set; }
        public string password { get; set; }
    }
}
