//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbModel : DbContext
    {
        public dbModel()
            : base("name=dbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DESIGNATION> DESIGNATIONs { get; set; }
        public virtual DbSet<ANG_EMPLOYEE> ANG_EMPLOYEE { get; set; }
        public virtual DbSet<PASSWORD> PASSWORDs { get; set; }
    }
}
