//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWORD
    {
        public long id { get; set; }
        public string username { get; set; }
        public string passwd { get; set; }
        public string EmpName { get; set; }
        public string FilePath { get; set; }
        public string Compcd { get; set; }
        public string EmpCode { get; set; }
        public string email { get; set; }
        public string EmpLastName { get; set; }
    }
}
